Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно

In [1]:
import numpy as np
a = np.arange(12, 24)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.

In [2]:
a_new = []
for i in range(2, 13):
    if a.size%i == 0:
        a_new.append(a.reshape(i, a.size//i))
a_new

[array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]),
 array([[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]),
 array([[12, 13],
        [14, 15],
        [16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]),
 array([[12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20],
        [21],
        [22],
        [23]])]

Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).

In [3]:
a_new = []
for i in range(2, 13):
    if a.size%i == 0:
        a_new.append(a.reshape(i, -1))
a_new

[array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]),
 array([[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]),
 array([[12, 13],
        [14, 15],
        [16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]),
 array([[12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20],
        [21],
        [22],
        [23]])]

In [4]:
a_new = []
for i in range(1, 12):
    if a.size%i == 0:
        a_new.append(a.reshape(-1, i))
a_new

[array([[12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20],
        [21],
        [22],
        [23]]),
 array([[12, 13],
        [14, 15],
        [16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]),
 array([[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]),
 array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]])]

Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным
Условно можно, но т.к. обращение к элементам будет в формате (1, j) - он по факту двумерный

Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

In [5]:
c = np.random.randn(3, 4)
c

array([[-0.02773405, -0.05529121,  0.26637391,  0.74999917],
       [ 0.95438889, -0.09825421, -1.77646022, -1.9428866 ],
       [-0.41006719, -0.98952681,  0.59332917,  0.14038185]])

In [6]:
c_new = c.reshape(12)
c_new

array([-0.02773405, -0.05529121,  0.26637391,  0.74999917,  0.95438889,
       -0.09825421, -1.77646022, -1.9428866 , -0.41006719, -0.98952681,
        0.59332917,  0.14038185])

Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.

In [7]:
c = np.arange(20, 0, -2)
c

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?

In [11]:
b = np.arange(20, 1, -2)
b = b.reshape(1,10)
b

array([[20, 18, 16, 14, 12, 10,  8,  6,  4,  2]])

In [12]:
print(f'{a == b}')

False


C:\Users\1\AppData\Local\Temp\ipykernel_8868\3481187355.py:1: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  print(f'{a == b}')


Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.

In [13]:
a = np.zeros((4, 2))
b = np.ones((5, 2))
c = np.vstack([a, b])
c

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?

In [14]:
a = np.arange(0, 12)
A = a.reshape(4,3)
At = A.transpose()
B = np.dot(A,At)
B.shape

(4, 4)

In [15]:
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [16]:
B_inv = np.linalg.inv(B)

LinAlgError: Singular matrix

Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.

In [18]:
np.random.seed(42)

Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно. 


In [19]:
c = np.random.uniform(0, 16, 16)
c

array([ 5.9926419 , 15.2114289 , 11.71190307,  9.57853575,  2.49629825,
        2.49591233,  0.92933779, 13.85881833,  9.61784019, 11.32916124,
        0.32935191, 15.51855763, 13.31908225,  3.39742577,  2.90919948,
        2.93447216])

Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D.


In [20]:
C = c.reshape(4, 4)
C

array([[ 5.9926419 , 15.2114289 , 11.71190307,  9.57853575],
       [ 2.49629825,  2.49591233,  0.92933779, 13.85881833],
       [ 9.61784019, 11.32916124,  0.32935191, 15.51855763],
       [13.31908225,  3.39742577,  2.90919948,  2.93447216]])

In [21]:
D = B + C * 10
D

array([[ 64.92641902, 166.11428903, 140.11903069, 127.78535747],
       [ 38.96298247,  74.95912325,  95.29337795, 260.58818332],
       [119.17840188, 199.29161245, 152.29351909, 367.18557635],
       [165.19082253, 155.97425771, 241.09199475, 331.34472158]])

In [22]:
np.linalg.det(D)

-237256363.53160015

In [23]:
np.linalg.matrix_rank(D)

4

In [25]:
D_inv = np.linalg.inv(D)
D_inv

array([[-0.01113732, -0.01874086,  0.01081617,  0.00704792],
       [ 0.0061776 , -0.00400992,  0.00582719, -0.00568631],
       [ 0.0076154 ,  0.00949829, -0.01337814,  0.00441831],
       [-0.00289661,  0.00431967,  0.00159876, -0.00103382]])

Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv остались только нули и единицы. С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4.  Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.


In [26]:
D_inv[D_inv < 0] = 0
D_inv[D_inv > 0] = 1
D_inv

array([[0., 0., 1., 1.],
       [1., 0., 1., 0.],
       [1., 1., 0., 1.],
       [0., 1., 1., 0.]])

In [29]:
E = np.where(D_inv == 0, C, B)
E

array([[  5.9926419 ,  15.2114289 ,  23.        ,  32.        ],
       [ 14.        ,   2.49591233,  86.        ,  13.85881833],
       [ 23.        ,  86.        ,   0.32935191, 212.        ],
       [ 13.31908225, 122.        , 212.        ,   2.93447216]])